---
# this playbook makes it so that localhost is the default target for ansible commands
- hosts: all
  remote_user: pi
  become: yes
  tasks:
  - name: manage hostfile
    lineinfile:
      path: /etc/ansible/hosts
      line: 'localhost ansible_connection=local'
