---
# this playbook installs and configures the web_flower server
- hosts: test-flowers
  remote_user: pi
  become: yes
  tasks:
  - name: setup directories
    file:
      path: '/srv'
      state: directory
      mode: 0755
  - name: check out code
    git:
      repo: https://github.com/bbulkow/MagnusFlora.git
      dest: /srv
      update: yes
  - name: update pip
    pip:
      name: pip
      executable: /usr/bin/pip3
  - name: insnall virtualenv
    pip:
      name: virtualenv
      executable: /usr/bin/pip3
  - name: install packages
    pip:
      requirements: /srv/flask/requirements.txt
      virtualenv: /srv/.virtualenv/
  - name: setup celery
    supervisorctl:
      name: flower_web
      state: restarted
      config: /srv/ansible/files/flask/celery_worker.conf
  - name: setup webserver
    supervisorctl:
      name: flower_web
      state: restarted
      config: /srv/ansible/files/flask/web_flower_server.conf
